#!/usr/bin/env python3
"""Run backend tests against a disposable, locally owned Oracle container."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import secrets
import signal
import subprocess
import sys
import time
import uuid


IMAGE = "gvenzl/oracle-free:23-slim-faststart"
LABEL = "com.external-news-agent.test-run"
CONTAINER_PREFIX = "external-news-test-db-"
USERNAME = "news_test"
BE_DIRECTORY = Path(__file__).resolve().parents[1]
DB_KEYS = ("URL", "USERNAME", "PASSWORD", "CONTAINER", "RUN_ID")
INSPECT_FORMAT = (
    '{"id":{{json .Id}},"label":{{json (index .Config.Labels "'
    + LABEL
    + '")}},"ports":{{json (index .NetworkSettings.Ports "1521/tcp")}},'
    '"running":{{json .State.Running}},'
    '"health":{{if .State.Health}}{{json .State.Health.Status}}{{else}}null{{end}},'
    '"user":"{{range .Config.Env}}{{if eq . "APP_USER=news_test"}}news_test{{end}}{{end}}"}'
)


class TestDbError(Exception):
    """An error whose message is safe to display without command output."""


class InterruptedRun(Exception):
    def __init__(self, signum: int):
        self.signum = signum
        super().__init__("Test run interrupted.")


def docker(arguments: list[str], *, environment: dict[str, str] | None = None,
           timeout: float = 30) -> str:
    try:
        result = subprocess.run(
            ["docker", *arguments], env=environment, capture_output=True,
            text=True, timeout=timeout, check=False,
        )
    except FileNotFoundError as error:
        raise TestDbError("Docker is not installed or is not on PATH.") from error
    except subprocess.TimeoutExpired as error:
        raise TestDbError("Docker command timed out.") from error
    except OSError as error:
        raise TestDbError("Docker could not be started.") from error
    if result.returncode:
        # Container startup output can contain generated database credentials.
        raise TestDbError("Docker command failed; check that the local Docker engine is available.")
    return result.stdout.strip()


def require_local_docker(environment: dict[str, str]) -> None:
    if environment.get("DOCKER_HOST") and not environment.get("DOCKER_CONTEXT"):
        endpoint = environment["DOCKER_HOST"]
    else:
        arguments = ["context", "inspect"]
        if environment.get("DOCKER_CONTEXT"):
            arguments.append(environment["DOCKER_CONTEXT"])
        arguments.extend(["--format", "{{json .Endpoints.docker.Host}}"])
        try:
            endpoint = json.loads(docker(arguments, environment=environment))
        except (json.JSONDecodeError, TypeError) as error:
            raise TestDbError("Docker context did not provide a valid local endpoint.") from error
    if not isinstance(endpoint, str) or not endpoint.startswith("unix:///"):
        raise TestDbError("Test databases require a local Docker Unix socket; remote Docker endpoints are refused.")


def read_configuration(environment: dict[str, str]) -> dict[str, str]:
    values = {key: environment.get("NEWS_TEST_DB_" + key, "") for key in DB_KEYS}
    if any(not value for value in values.values()):
        raise TestDbError("Missing NEWS_TEST_DB configuration. Run python3 scripts/test-db.py.")
    run_id = values["RUN_ID"]
    if not re.fullmatch(r"[0-9a-f]{32}", run_id):
        raise TestDbError("Invalid test database run identity.")
    if values["CONTAINER"] != CONTAINER_PREFIX + run_id:
        raise TestDbError("Test database container name does not match its run identity.")
    if values["USERNAME"] != USERNAME:
        raise TestDbError("Only the dedicated news_test database user is allowed.")
    match = re.fullmatch(r"jdbc:oracle:thin:@127\.0\.0\.1:([1-9][0-9]{0,4})/FREEPDB1", values["URL"])
    if not match or not 1024 <= int(match[1]) <= 65535 or int(match[1]) == 1521:
        raise TestDbError("Test database URL must use its dedicated loopback port, never operational port 1521.")
    if len(values["PASSWORD"]) < 16:
        raise TestDbError("Test database credentials must be generated by the isolated launcher.")
    return values


def inspect_container(container: str, environment: dict[str, str]) -> dict:
    try:
        metadata = json.loads(docker(
            ["inspect", "--type", "container", "--format", INSPECT_FORMAT, container],
            environment=environment,
        ))
    except (json.JSONDecodeError, TypeError) as error:
        raise TestDbError("Docker returned invalid test container metadata.") from error
    if not isinstance(metadata, dict):
        raise TestDbError("Docker returned invalid test container metadata.")
    return metadata


def check_ownership(metadata: dict, run_id: str) -> str:
    container_id = metadata.get("id")
    if metadata.get("label") != run_id or not isinstance(container_id, str) or not re.fullmatch(r"[0-9a-f]{64}", container_id):
        raise TestDbError("Container ownership does not match this test run; no container will be removed.")
    return container_id


def published_port(metadata: dict) -> int:
    ports = metadata.get("ports")
    if not isinstance(ports, list) or len(ports) != 1 or not isinstance(ports[0], dict):
        raise TestDbError("Test container must publish exactly one Oracle loopback port.")
    binding = ports[0]
    raw_port = binding.get("HostPort")
    if (binding.get("HostIp") != "127.0.0.1" or not isinstance(raw_port, str)
            or not re.fullmatch(r"[1-9][0-9]{0,4}", raw_port)):
        raise TestDbError("Oracle test port is not bound exclusively to loopback.")
    port = int(raw_port)
    if not 1024 <= port <= 65535 or port == 1521:
        raise TestDbError("Oracle test container is using an unsafe host port.")
    return port


def validate(environment: dict[str, str]) -> None:
    values = read_configuration(environment)
    require_local_docker(environment)
    metadata = inspect_container(values["CONTAINER"], environment)
    check_ownership(metadata, values["RUN_ID"])
    if metadata.get("user") != USERNAME:
        raise TestDbError("Container does not have the dedicated test database user.")
    if metadata.get("running") is not True or metadata.get("health") != "healthy":
        raise TestDbError("The owned Oracle test container is not running and healthy.")
    if values["URL"] != f"jdbc:oracle:thin:@127.0.0.1:{published_port(metadata)}/FREEPDB1":
        raise TestDbError("Test database URL does not match the owned container port.")


def remove_owned_container(container: str, run_id: str, environment: dict[str, str]) -> bool:
    """Only remove an inspected immutable ID carrying this run's ownership label."""
    if not re.fullmatch(r"[0-9a-f]{32}", run_id) or container != CONTAINER_PREFIX + run_id:
        raise TestDbError("Refusing cleanup without a valid test run identity.")
    metadata = inspect_container(container, environment)
    container_id = check_ownership(metadata, run_id)
    docker(["rm", "--force", "--volumes", container_id], environment=environment)
    return True


def wait_until_healthy(container: str, run_id: str, environment: dict[str, str],
                       timeout: float = 300) -> int:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        metadata = inspect_container(container, environment)
        check_ownership(metadata, run_id)
        if metadata.get("running") is not True or metadata.get("health") == "unhealthy":
            raise TestDbError("The isolated Oracle container failed to start.")
        if metadata.get("health") == "healthy":
            if metadata.get("user") != USERNAME:
                raise TestDbError("The isolated Oracle container has an unexpected database user.")
            return published_port(metadata)
        time.sleep(2)
    raise TestDbError("Timed out waiting for the isolated Oracle test database.")


def child_environment(environment: dict[str, str]) -> dict[str, str]:
    prefixes = ("SPRING_", "SPRING.", "NEWS_", "NEWS.", "AGENT_", "NAVER_", "TAVILY_",
                "SERPAPI_", "OPENAI_", "MINDLOGIC_", "SMTP_", "TELEGRAM_", "BREAKING_",
                "ORG_GRADLE_PROJECT_")
    jvm_options = {"JAVA_TOOL_OPTIONS", "JDK_JAVA_OPTIONS", "_JAVA_OPTIONS", "JAVA_OPTS", "GRADLE_OPTS"}
    return {key: value for key, value in environment.items()
            if key.upper() not in jvm_options and not key.upper().startswith(prefixes)}


def run_gradle(environment: dict[str, str], patterns: list[str]) -> int:
    arguments = [str(BE_DIRECTORY / "gradlew"), "test", "-Dnews.integration.db=true",
                 "--no-daemon", "--rerun-tasks"]
    for pattern in patterns:
        arguments.extend(["--tests", pattern])
    try:
        process = subprocess.Popen(arguments, cwd=BE_DIRECTORY, env=environment, start_new_session=True)
    except OSError as error:
        raise TestDbError("The backend Gradle wrapper could not be started.") from error
    try:
        return process.wait()
    except BaseException:
        try:
            os.killpg(process.pid, signal.SIGTERM)
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                os.killpg(process.pid, signal.SIGKILL)
                process.wait(timeout=5)
        except ProcessLookupError:
            pass
        raise


def launch(environment: dict[str, str], patterns: list[str]) -> int:
    require_local_docker(environment)
    run_id = uuid.uuid4().hex
    container = CONTAINER_PREFIX + run_id
    password = secrets.token_hex(24) + "Aa1"
    docker_environment = dict(environment)
    docker_environment.update(APP_USER=USERNAME, APP_USER_PASSWORD=password,
                              ORACLE_PASSWORD=secrets.token_hex(24) + "Aa1")
    cleanup_failed = False
    try:
        print("Starting an isolated Oracle test database...", flush=True)
        docker(["run", "--detach", "--name", container, "--label", LABEL + "=" + run_id,
                "--env", "APP_USER", "--env", "APP_USER_PASSWORD", "--env", "ORACLE_PASSWORD",
                "--publish", "127.0.0.1::1521", "--health-cmd", "healthcheck.sh",
                "--health-interval", "5s", "--health-timeout", "5s",
                "--health-start-period", "30s", "--health-retries", "60", IMAGE],
               environment=docker_environment, timeout=180)
        port = wait_until_healthy(container, run_id, environment)
        gradle_environment = child_environment(environment)
        gradle_environment.update({
            "NEWS_TEST_DB_URL": f"jdbc:oracle:thin:@127.0.0.1:{port}/FREEPDB1",
            "NEWS_TEST_DB_USERNAME": USERNAME,
            "NEWS_TEST_DB_PASSWORD": password,
            "NEWS_TEST_DB_CONTAINER": container,
            "NEWS_TEST_DB_RUN_ID": run_id,
        })
        validate(gradle_environment)
        print("Running backend tests against the isolated database...", flush=True)
        result = run_gradle(gradle_environment, patterns)
    finally:
        # Let bounded cleanup finish even if another termination signal arrives.
        previous_handlers = {sig: signal.signal(sig, signal.SIG_IGN) for sig in (signal.SIGINT, signal.SIGTERM)}
        try:
            remove_owned_container(container, run_id, environment)
            print("Removed the owned Oracle test container and its anonymous volumes.", flush=True)
        except TestDbError:
            cleanup_failed = True
            print(f"Test container cleanup could not be confirmed; inspect {container} manually.", file=sys.stderr)
        finally:
            for sig, handler in previous_handlers.items():
                signal.signal(sig, handler)
    return 2 if cleanup_failed and result == 0 else result


def main(arguments: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--validate", action="store_true", help="verify launcher-owned DB settings without opening a DB connection")
    parser.add_argument("--tests", action="append", default=[], metavar="PATTERN", help="run a Gradle test class/method pattern")
    options = parser.parse_args(arguments)
    if options.validate and options.tests:
        parser.error("--validate cannot be combined with --tests")
    if any(not pattern or pattern.startswith("-") for pattern in options.tests):
        parser.error("--tests requires a test class/method pattern, not a Gradle option")

    def interrupted(signum: int, _frame: object) -> None:
        raise InterruptedRun(signum)

    previous_handlers = {sig: signal.signal(sig, interrupted) for sig in (signal.SIGINT, signal.SIGTERM)}
    try:
        environment = dict(os.environ)
        if options.validate:
            validate(environment)
            return 0
        return launch(environment, options.tests)
    except TestDbError as error:
        print(f"Test database error: {error}", file=sys.stderr)
        return 2
    except InterruptedRun as error:
        print("Test run interrupted; owned container cleanup was attempted.", file=sys.stderr)
        return 128 + error.signum
    finally:
        for sig, handler in previous_handlers.items():
            signal.signal(sig, handler)


if __name__ == "__main__":
    sys.exit(main())
