-- A3 플랜 선택과 durable quota 예약. 실제 사용량 메타는 계속 agent_runs가 보유하고,
-- 예약 테이블은 동시 Agent 호출이 한도를 넘기지 않게 inflight 사용량을 선점한다.
ALTER TABLE news_collection_runs ADD (
    llm_plan VARCHAR2(10) DEFAULT 'FREE' NOT NULL
);

ALTER TABLE news_collection_runs ADD CONSTRAINT ck_collection_run_llm_plan
    CHECK (llm_plan IN ('FREE', 'PAID'));

CREATE TABLE app_settings (
    id                    NUMBER DEFAULT 1 NOT NULL PRIMARY KEY,
    llm_plan              VARCHAR2(10) DEFAULT 'FREE' NOT NULL,
    paid_exhausted_action VARCHAR2(20) DEFAULT 'STUB' NOT NULL,
    updated_at            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_app_settings_singleton CHECK (id = 1),
    CONSTRAINT ck_app_settings_plan CHECK (llm_plan IN ('FREE', 'PAID')),
    CONSTRAINT ck_app_settings_exhausted CHECK (paid_exhausted_action IN ('STUB', 'FALLBACK_FREE'))
);

INSERT INTO app_settings (id) VALUES (1);

CREATE TABLE agent_quota_reservations (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_run_id NUMBER REFERENCES news_collection_runs (id),
    idempotency_key   VARCHAR2(200) NOT NULL,
    agent_task        VARCHAR2(50) NOT NULL,
    llm_plan          VARCHAR2(10) NOT NULL,
    reserved_units    NUMBER(10,3) NOT NULL,
    consumed_units    NUMBER(10,3),
    status            VARCHAR2(20) NOT NULL,
    reserved_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    finished_at       TIMESTAMP,
    CONSTRAINT uq_agent_quota_idempotency UNIQUE (idempotency_key),
    CONSTRAINT ck_agent_quota_task CHECK (agent_task IN ('ANALYZE', 'VERIFY_EVIDENCE', 'REPORT', 'EXPLORE')),
    CONSTRAINT ck_agent_quota_plan CHECK (llm_plan IN ('FREE', 'PAID')),
    CONSTRAINT ck_agent_quota_status CHECK (status IN ('RESERVED', 'CONSUMED', 'RELEASED')),
    CONSTRAINT ck_agent_quota_units CHECK (
        reserved_units > 0 AND (consumed_units IS NULL OR consumed_units >= 0)
    )
);

CREATE INDEX ix_agent_quota_usage
    ON agent_quota_reservations (llm_plan, reserved_at, status);
CREATE INDEX ix_agent_quota_run
    ON agent_quota_reservations (collection_run_id, agent_task, status);
