CREATE TABLE schema_version_check (
                                      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);