-- M6 알림 채널 추상화. 비밀값은 환경변수에만 두고 DB에는 공개 설정만 저장한다.
CREATE TABLE notification_channels (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_type      VARCHAR2(20) NOT NULL,
    name              VARCHAR2(100) NOT NULL,
    config_json       CLOB DEFAULT '{}' NOT NULL,
    max_length        NUMBER(10) NOT NULL,
    active_yn         CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT uq_notification_channel_type UNIQUE (channel_type),
    CONSTRAINT ck_notification_channel_type CHECK (channel_type IN ('TELEGRAM', 'EMAIL')),
    CONSTRAINT ck_notification_channel_config CHECK (config_json IS JSON),
    CONSTRAINT ck_notification_channel_length CHECK (max_length > 0),
    CONSTRAINT ck_notification_channel_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE notification_recipients (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    phone       VARCHAR2(30),
    email       VARCHAR2(320),
    memo        VARCHAR2(1000),
    active_yn   CHAR(1) DEFAULT 'Y' NOT NULL,
    deleted_at  TIMESTAMP,
    CONSTRAINT ck_notification_recipient_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE notification_recipient_destinations (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id   NUMBER NOT NULL,
    channel_id     NUMBER NOT NULL,
    address        VARCHAR2(500),
    use_yn         CHAR(1) DEFAULT 'Y' NOT NULL,
    onboarded_yn   CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT fk_destination_recipient FOREIGN KEY (recipient_id) REFERENCES notification_recipients (id),
    CONSTRAINT fk_destination_channel FOREIGN KEY (channel_id) REFERENCES notification_channels (id),
    CONSTRAINT uq_destination_recipient_channel UNIQUE (recipient_id, channel_id),
    CONSTRAINT uq_destination_channel_address UNIQUE (channel_id, address),
    CONSTRAINT ck_destination_use CHECK (use_yn IN ('Y', 'N')),
    CONSTRAINT ck_destination_onboarded CHECK (onboarded_yn IN ('Y', 'N')),
    CONSTRAINT ck_destination_active_address CHECK (use_yn = 'N' OR address IS NOT NULL)
);

CREATE TABLE notification_groups (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(100) NOT NULL,
    perspective  VARCHAR2(30),
    active_yn    CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_notification_group_name UNIQUE (name),
    CONSTRAINT ck_notification_group_perspective CHECK (
        perspective IS NULL OR perspective IN ('EXECUTIVE', 'PURCHASING', 'TECHNOLOGY', 'SALES')),
    CONSTRAINT ck_notification_group_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE notification_group_members (
    group_id      NUMBER NOT NULL,
    recipient_id  NUMBER NOT NULL,
    CONSTRAINT pk_notification_group_member PRIMARY KEY (group_id, recipient_id),
    CONSTRAINT fk_group_member_group FOREIGN KEY (group_id) REFERENCES notification_groups (id),
    CONSTRAINT fk_group_member_recipient FOREIGN KEY (recipient_id) REFERENCES notification_recipients (id)
);

CREATE TABLE notification_delivery_batches (
    id               VARCHAR2(36) PRIMARY KEY,
    report_id        NUMBER NOT NULL,
    idempotency_key  VARCHAR2(100),
    requested_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_delivery_batch_report FOREIGN KEY (report_id) REFERENCES news_reports (id),
    CONSTRAINT uq_delivery_idempotency_key UNIQUE (idempotency_key)
);

CREATE TABLE notification_delivery_logs (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_batch_id    VARCHAR2(36) NOT NULL,
    report_id            NUMBER NOT NULL,
    recipient_id         NUMBER NOT NULL,
    recipient_name       VARCHAR2(100) NOT NULL,
    channel_id           NUMBER NOT NULL,
    channel_type         VARCHAR2(20) NOT NULL,
    address              VARCHAR2(500) NOT NULL,
    status               VARCHAR2(20) NOT NULL,
    external_message_id  VARCHAR2(500),
    chunk_seq            NUMBER(10),
    chunk_count          NUMBER(10),
    error_message        VARCHAR2(1000),
    sent_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_delivery_log_batch FOREIGN KEY (delivery_batch_id) REFERENCES notification_delivery_batches (id),
    CONSTRAINT fk_delivery_log_report FOREIGN KEY (report_id) REFERENCES news_reports (id),
    CONSTRAINT fk_delivery_log_recipient FOREIGN KEY (recipient_id) REFERENCES notification_recipients (id),
    CONSTRAINT fk_delivery_log_channel FOREIGN KEY (channel_id) REFERENCES notification_channels (id),
    CONSTRAINT ck_delivery_log_channel CHECK (channel_type IN ('TELEGRAM', 'EMAIL')),
    CONSTRAINT ck_delivery_log_status CHECK (status IN ('SENT', 'FAILED', 'SKIPPED')),
    CONSTRAINT ck_delivery_log_chunks CHECK (
        (chunk_seq IS NULL AND chunk_count IS NULL) OR
        (chunk_seq BETWEEN 1 AND chunk_count))
);

CREATE INDEX ix_notification_recipient_active ON notification_recipients (active_yn, id);
CREATE INDEX ix_notification_group_active ON notification_groups (active_yn, id);
CREATE INDEX ix_notification_member_recipient ON notification_group_members (recipient_id, group_id);
CREATE INDEX ix_delivery_log_report ON notification_delivery_logs (report_id, sent_at DESC, id DESC);
CREATE INDEX ix_delivery_log_batch ON notification_delivery_logs (delivery_batch_id, id);
CREATE INDEX ix_delivery_log_filters ON notification_delivery_logs (channel_type, status, sent_at DESC);

INSERT INTO notification_channels (id, channel_type, name, config_json, max_length, active_yn)
VALUES (1, 'TELEGRAM', '텔레그램 속보', '{"parseMode":"HTML","disableWebPagePreview":true}', 3500, 'Y');

INSERT INTO notification_channels (id, channel_type, name, config_json, max_length, active_yn)
VALUES (2, 'EMAIL', '메일 보고서', '{"host":"localhost","port":1025,"from":"news-agent@local.test"}', 2147483647, 'Y');
