-- P1-1. 같은 사건을 다루는 기사 묶음과 본문 중복군을 1급 객체로 올린다.
-- 기사 행은 삭제하지 않는다. 전재·신디케이션도 provenance로 보존하고 content_group_id로만 표시한다.

CREATE TABLE news_content_groups (
    id                        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    representative_article_id NUMBER NOT NULL,
    simhash                   VARCHAR2(16) NOT NULL,
    created_at                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_content_group_representative
        FOREIGN KEY (representative_article_id) REFERENCES news_articles (id),
    CONSTRAINT uq_content_group_representative UNIQUE (representative_article_id),
    CONSTRAINT ck_content_group_simhash CHECK (REGEXP_LIKE(simhash, '^[0-9a-f]{16}$'))
);

ALTER TABLE news_articles ADD content_group_id NUMBER;
ALTER TABLE news_articles ADD CONSTRAINT fk_article_content_group
    FOREIGN KEY (content_group_id) REFERENCES news_content_groups (id);
CREATE INDEX ix_article_content_group ON news_articles (content_group_id);

CREATE TABLE news_issues (
    id                        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                     VARCHAR2(1000) NOT NULL,
    summary                   CLOB,
    status                    VARCHAR2(20) DEFAULT 'EMERGING' NOT NULL,
    importance_score          NUMBER(6, 2),
    sensitivity_score         NUMBER(6, 2),
    first_seen_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    article_count             NUMBER(10) DEFAULT 0 NOT NULL,
    publisher_count           NUMBER(10) DEFAULT 0 NOT NULL,
    independent_content_count NUMBER(10) DEFAULT 0 NOT NULL,
    topic_id                  NUMBER NOT NULL,
    entities                  CLOB DEFAULT '[]' NOT NULL,
    cross_source              CLOB DEFAULT '{"consensus":[],"soleSource":[],"conflicts":[],"missingStakeholders":[]}' NOT NULL,
    CONSTRAINT fk_issue_topic FOREIGN KEY (topic_id) REFERENCES news_topics (id),
    CONSTRAINT ck_issue_status CHECK (status IN ('EMERGING', 'CORROBORATED', 'DISPUTED', 'RETRACTED')),
    CONSTRAINT ck_issue_scores CHECK (
        (importance_score IS NULL OR importance_score BETWEEN 0 AND 100)
        AND (sensitivity_score IS NULL OR sensitivity_score BETWEEN 0 AND 100)
    ),
    CONSTRAINT ck_issue_counts CHECK (
        article_count >= 0 AND publisher_count >= 0 AND independent_content_count >= 0
    ),
    CONSTRAINT ck_issue_entities_json CHECK (entities IS JSON),
    CONSTRAINT ck_issue_cross_source_json CHECK (cross_source IS JSON)
);

CREATE INDEX ix_issue_topic_last_seen ON news_issues (topic_id, last_seen_at DESC);

CREATE TABLE news_issue_articles (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id          NUMBER NOT NULL,
    article_id        NUMBER NOT NULL,
    role              VARCHAR2(20) NOT NULL,
    stance            VARCHAR2(20) DEFAULT 'SUPPORTS' NOT NULL,
    stance_source     VARCHAR2(10) DEFAULT 'RULE' NOT NULL,
    stance_confidence NUMBER(4, 3) DEFAULT 1 NOT NULL,
    joined_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_issue_article_issue FOREIGN KEY (issue_id) REFERENCES news_issues (id),
    CONSTRAINT fk_issue_article_article FOREIGN KEY (article_id) REFERENCES news_articles (id),
    CONSTRAINT uq_issue_article UNIQUE (issue_id, article_id),
    CONSTRAINT ck_issue_article_role CHECK (role IN ('REPRESENTATIVE', 'MEMBER', 'BREAKING')),
    CONSTRAINT ck_issue_article_stance CHECK (stance IN ('SUPPORTS', 'ADDS', 'DISPUTES', 'RETRACTS')),
    CONSTRAINT ck_issue_article_stance_source CHECK (stance_source IN ('RULE', 'LLM')),
    CONSTRAINT ck_issue_article_confidence CHECK (stance_confidence BETWEEN 0 AND 1)
);

CREATE INDEX ix_issue_article_article ON news_issue_articles (article_id);

CREATE TABLE news_issue_relations (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_issue_id NUMBER NOT NULL,
    to_issue_id   NUMBER NOT NULL,
    relation_type VARCHAR2(20) NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_issue_relation_from FOREIGN KEY (from_issue_id) REFERENCES news_issues (id),
    CONSTRAINT fk_issue_relation_to FOREIGN KEY (to_issue_id) REFERENCES news_issues (id),
    CONSTRAINT uq_issue_relation UNIQUE (from_issue_id, to_issue_id, relation_type),
    CONSTRAINT ck_issue_relation_type CHECK (relation_type IN ('REFUTES', 'UPDATES', 'BACKGROUND')),
    CONSTRAINT ck_issue_relation_distinct CHECK (from_issue_id <> to_issue_id)
);

CREATE TABLE news_issue_status_history (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id    NUMBER NOT NULL,
    from_status VARCHAR2(20),
    to_status   VARCHAR2(20) NOT NULL,
    reason      VARCHAR2(1000),
    changed_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_issue_status_history_issue FOREIGN KEY (issue_id) REFERENCES news_issues (id),
    CONSTRAINT ck_issue_history_from_status CHECK (
        from_status IS NULL OR from_status IN ('EMERGING', 'CORROBORATED', 'DISPUTED', 'RETRACTED')
    ),
    CONSTRAINT ck_issue_history_to_status CHECK (
        to_status IN ('EMERGING', 'CORROBORATED', 'DISPUTED', 'RETRACTED')
    )
);

CREATE INDEX ix_issue_status_history_issue ON news_issue_status_history (issue_id, changed_at DESC);
