-- P1-4. 규칙 기반 속보 감지 후 같은 이슈에 붙는 후속 기사를 알림 채널로 추적한다.
CREATE TABLE news_watches (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watch_type           VARCHAR2(30) NOT NULL,
    issue_id             NUMBER NOT NULL,
    sensitivity_at_watch NUMBER(6, 2),
    notify_group_id      NUMBER,
    cooldown_until       TIMESTAMP,
    expires_at           TIMESTAMP NOT NULL,
    active_yn            CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT fk_watch_issue FOREIGN KEY (issue_id) REFERENCES news_issues (id),
    CONSTRAINT fk_watch_notify_group FOREIGN KEY (notify_group_id)
        REFERENCES notification_groups (id) ON DELETE SET NULL,
    CONSTRAINT uq_watch_issue_type UNIQUE (issue_id, watch_type),
    CONSTRAINT ck_watch_type CHECK (
        watch_type IN ('BREAKING', 'DISPUTED', 'HIGH_SENSITIVITY', 'HYPOTHESIS', 'MANUAL')),
    CONSTRAINT ck_watch_sensitivity CHECK (
        sensitivity_at_watch IS NULL OR sensitivity_at_watch BETWEEN 0 AND 100),
    CONSTRAINT ck_watch_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE INDEX ix_watch_notification_due
    ON news_watches (issue_id, active_yn, expires_at, cooldown_until);
