-- 속보 후속 알림은 이슈 갱신과 같은 트랜잭션에서 먼저 기록한 뒤 외부 채널로 발송한다.
CREATE TABLE watch_notification_outbox (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watch_id              NUMBER NOT NULL,
    notify_group_id       NUMBER,
    issue_title           VARCHAR2(1000) NOT NULL,
    first_seen_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    follow_up_count       NUMBER(10) NOT NULL,
    publisher_count       NUMBER(10) NOT NULL,
    queued_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    status                VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    attempt_count         NUMBER(10) DEFAULT 0 NOT NULL,
    processing_started_at TIMESTAMP,
    delivered_at          TIMESTAMP,
    last_error            VARCHAR2(1000),
    CONSTRAINT fk_watch_alert_watch FOREIGN KEY (watch_id)
        REFERENCES news_watches (id),
    CONSTRAINT fk_watch_alert_group FOREIGN KEY (notify_group_id)
        REFERENCES notification_groups (id) ON DELETE SET NULL,
    CONSTRAINT ck_watch_alert_status CHECK (status IN ('PENDING', 'PROCESSING', 'SENT')),
    CONSTRAINT ck_watch_alert_attempt CHECK (attempt_count >= 0)
);

CREATE INDEX ix_watch_alert_claim
    ON watch_notification_outbox (status, processing_started_at, id);
