CREATE TABLE news_sources (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind       VARCHAR2(10) NOT NULL,
    name              VARCHAR2(200) NOT NULL,
    url_template      VARCHAR2(1000) NOT NULL,
    country           VARCHAR2(2),
    language          VARCHAR2(5),
    crawl_policy      CLOB,
    robots_status     VARCHAR2(20),
    robots_checked_at TIMESTAMP,
    reliability_score NUMBER(3, 2),
    active_yn         CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT ck_source_kind CHECK (source_kind IN ('FEED', 'SEARCH')),
    CONSTRAINT ck_source_active_yn CHECK (active_yn IN ('Y', 'N')),
    CONSTRAINT ck_source_policy CHECK (crawl_policy IS JSON),
    CONSTRAINT uq_news_source UNIQUE (source_kind, url_template)
);

CREATE TABLE news_topics (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR2(200) NOT NULL,
    query_text        VARCHAR2(500),
    required_keywords CLOB,
    optional_keywords CLOB,
    excluded_keywords CLOB,
    batch_size        NUMBER(4) DEFAULT 10 NOT NULL,
    interval_minutes  NUMBER(6) DEFAULT 60 NOT NULL,
    active_yn         CHAR(1) DEFAULT 'Y' NOT NULL,
    last_collected_at TIMESTAMP,
    CONSTRAINT uq_news_topic_name UNIQUE (name),
    CONSTRAINT ck_topic_active_yn CHECK (active_yn IN ('Y', 'N')),
    CONSTRAINT ck_topic_batch_size CHECK (batch_size BETWEEN 1 AND 100),
    CONSTRAINT ck_topic_interval CHECK (interval_minutes >= 10),
    CONSTRAINT ck_topic_required_keywords CHECK (required_keywords IS JSON),
    CONSTRAINT ck_topic_optional_keywords CHECK (optional_keywords IS JSON),
    CONSTRAINT ck_topic_excluded_keywords CHECK (excluded_keywords IS JSON)
);

CREATE TABLE news_topic_sources (
    topic_id  NUMBER NOT NULL,
    source_id NUMBER NOT NULL,
    CONSTRAINT pk_news_topic_sources PRIMARY KEY (topic_id, source_id),
    CONSTRAINT fk_topic_sources_topic FOREIGN KEY (topic_id) REFERENCES news_topics (id),
    CONSTRAINT fk_topic_sources_source FOREIGN KEY (source_id) REFERENCES news_sources (id)
);

CREATE INDEX ix_topic_sources_source ON news_topic_sources (source_id);
