-- A9. 이슈 단위 관점 인사이트를 온디맨드로 저장하고 동일 입력·프롬프트를 재사용한다.
CREATE TABLE news_insights (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type         VARCHAR2(20) DEFAULT 'ISSUE' NOT NULL,
    target_id           NUMBER NOT NULL,
    audience            VARCHAR2(30) NOT NULL,
    headline            VARCHAR2(500 CHAR) NOT NULL,
    facts_json          CLOB DEFAULT '[]' NOT NULL,
    implications_json   CLOB DEFAULT '[]' NOT NULL,
    watch_next_json     CLOB DEFAULT '[]' NOT NULL,
    confidence          NUMBER(4,3),
    input_hash          VARCHAR2(64) NOT NULL,
    prompt_version      VARCHAR2(50) NOT NULL,
    llm_provider        VARCHAR2(30),
    llm_model           VARCHAR2(100),
    input_tokens        NUMBER,
    output_tokens       NUMBER,
    cost_usd            NUMBER(12,6),
    credits             NUMBER(10,3),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_insight_issue FOREIGN KEY (target_id) REFERENCES news_issues (id),
    CONSTRAINT ck_insight_target CHECK (target_type = 'ISSUE'),
    CONSTRAINT ck_insight_audience CHECK (audience IN
        ('CHIP_MAKER', 'EQUIPMENT_MAKER', 'MARKET_INVESTOR', 'IT_INFRA')),
    CONSTRAINT ck_insight_facts_json CHECK (facts_json IS JSON),
    CONSTRAINT ck_insight_implications_json CHECK (implications_json IS JSON),
    CONSTRAINT ck_insight_watch_next_json CHECK (watch_next_json IS JSON),
    CONSTRAINT ck_insight_confidence CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    CONSTRAINT uq_insight UNIQUE (
        target_type, target_id, audience, input_hash, prompt_version
    )
);

CREATE INDEX ix_insight_target_created
    ON news_insights (target_type, target_id, created_at DESC);

ALTER TABLE agent_runs DROP CONSTRAINT ck_agent_task;
ALTER TABLE agent_runs ADD CONSTRAINT ck_agent_task
    CHECK (agent_task IN (
        'ANALYZE', 'SELF_CRITIQUE', 'VERIFY_EVIDENCE', 'REPORT', 'EXPLORE', 'INSIGHT'
    ));

ALTER TABLE agent_quota_reservations DROP CONSTRAINT ck_agent_quota_task;
ALTER TABLE agent_quota_reservations ADD CONSTRAINT ck_agent_quota_task
    CHECK (agent_task IN (
        'ANALYZE', 'SELF_CRITIQUE', 'VERIFY_EVIDENCE', 'REPORT', 'EXPLORE', 'INSIGHT'
    ));
