-- P2-5/P2-6. 조사 루프 상태는 Oracle이 소유하고 각 Agent 제안은 agent_runs로 감사한다.
CREATE TABLE news_issue_investigations (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_run_id       NUMBER NOT NULL REFERENCES news_collection_runs (id),
    issue_id                NUMBER NOT NULL REFERENCES news_issues (id),
    idempotency_key         VARCHAR2(200) NOT NULL,
    status                  VARCHAR2(30) DEFAULT 'IN_PROGRESS' NOT NULL,
    trigger_reason          VARCHAR2(1000 CHAR) NOT NULL,
    next_step               NUMBER(1) DEFAULT 1 NOT NULL,
    in_flight_step          NUMBER(1),
    evidence_count_before   NUMBER DEFAULT 0 NOT NULL,
    evidence_count_current  NUMBER DEFAULT 0 NOT NULL,
    added_article_count     NUMBER DEFAULT 0 NOT NULL,
    first_action_reason     VARCHAR2(1000 CHAR),
    rejection_reason        VARCHAR2(1000 CHAR),
    termination_reason      VARCHAR2(30),
    started_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    finished_at             TIMESTAMP,
    CONSTRAINT uq_issue_investigation_run UNIQUE (collection_run_id, issue_id),
    CONSTRAINT uq_issue_investigation_key UNIQUE (idempotency_key),
    CONSTRAINT ck_issue_investigation_status CHECK (
        status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED')
    ),
    CONSTRAINT ck_issue_investigation_step CHECK (
        next_step BETWEEN 1 AND 4
        AND (in_flight_step IS NULL OR in_flight_step BETWEEN 1 AND 3)
    ),
    CONSTRAINT ck_issue_investigation_counts CHECK (
        evidence_count_before >= 0
        AND evidence_count_current >= 0
        AND added_article_count >= 0
    ),
    CONSTRAINT ck_issue_investigation_termination CHECK (
        termination_reason IS NULL OR termination_reason IN (
            'CONCLUDED', 'NO_NEW_EVIDENCE', 'MAX_STEPS', 'BUDGET_LIMIT',
            'REJECTED', 'FAILED'
        )
    )
);

CREATE INDEX ix_issue_investigation_issue_started
    ON news_issue_investigations (issue_id, started_at DESC);

ALTER TABLE agent_runs ADD (
    investigation_step NUMBER(1),
    investigation_action VARCHAR2(30),
    action_reason VARCHAR2(1000 CHAR),
    source_key VARCHAR2(100),
    query_hash VARCHAR2(64),
    action_payload CLOB,
    rejection_reason VARCHAR2(1000 CHAR),
    added_article_count NUMBER DEFAULT 0 NOT NULL,
    evidence_before NUMBER,
    evidence_after NUMBER,
    termination_reason VARCHAR2(30)
);

ALTER TABLE agent_runs ADD CONSTRAINT ck_agent_investigation_step
    CHECK (investigation_step IS NULL OR investigation_step BETWEEN 1 AND 3);
ALTER TABLE agent_runs ADD CONSTRAINT ck_agent_action_payload
    CHECK (action_payload IS NULL OR action_payload IS JSON);
ALTER TABLE agent_runs ADD CONSTRAINT ck_agent_investigation_counts
    CHECK (
        added_article_count >= 0
        AND (evidence_before IS NULL OR evidence_before >= 0)
        AND (evidence_after IS NULL OR evidence_after >= 0)
    );

ALTER TABLE agent_runs DROP CONSTRAINT ck_agent_task;
ALTER TABLE agent_runs ADD CONSTRAINT ck_agent_task
    CHECK (agent_task IN (
        'ANALYZE', 'SELF_CRITIQUE', 'VERIFY_EVIDENCE', 'REPORT', 'EXPLORE',
        'INSIGHT', 'INVESTIGATE'
    ));

ALTER TABLE agent_quota_reservations DROP CONSTRAINT ck_agent_quota_task;
ALTER TABLE agent_quota_reservations ADD CONSTRAINT ck_agent_quota_task
    CHECK (agent_task IN (
        'ANALYZE', 'SELF_CRITIQUE', 'VERIFY_EVIDENCE', 'REPORT', 'EXPLORE',
        'INSIGHT', 'INVESTIGATE'
    ));

CREATE INDEX ix_agent_investigation_query
    ON agent_runs (collection_run_id, agent_task, query_hash);
