-- P2-7. 수집 전략가 제안은 별도로 저장하고 사람 승인 전에는 topic 키워드를 바꾸지 않는다.
CREATE TABLE news_topic_keyword_proposals (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id            NUMBER NOT NULL REFERENCES news_topics (id),
    collection_run_id   NUMBER NOT NULL REFERENCES news_collection_runs (id),
    idempotency_key     VARCHAR2(200 CHAR) NOT NULL,
    summary             VARCHAR2(1000 CHAR) NOT NULL,
    changes_json        CLOB DEFAULT '[]' NOT NULL,
    status              VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    reviewed_at         TIMESTAMP,
    CONSTRAINT uq_topic_keyword_proposal_run UNIQUE (collection_run_id, topic_id),
    CONSTRAINT uq_topic_keyword_proposal_key UNIQUE (idempotency_key),
    CONSTRAINT ck_topic_keyword_changes_json CHECK (changes_json IS JSON),
    CONSTRAINT ck_topic_keyword_proposal_status CHECK (
        status IN ('PENDING', 'APPROVED', 'REJECTED')
    )
);

CREATE INDEX ix_topic_keyword_proposal_status_created
    ON news_topic_keyword_proposals (status, created_at DESC, id DESC);

ALTER TABLE agent_runs DROP CONSTRAINT ck_agent_task;
ALTER TABLE agent_runs ADD CONSTRAINT ck_agent_task
    CHECK (agent_task IN (
        'ANALYZE', 'SELF_CRITIQUE', 'VERIFY_EVIDENCE', 'REPORT', 'EXPLORE',
        'INSIGHT', 'INVESTIGATE', 'KEYWORD_STRATEGY'
    ));

ALTER TABLE agent_runs DROP CONSTRAINT ck_agent_target_type;
ALTER TABLE agent_runs ADD CONSTRAINT ck_agent_target_type
    CHECK (target_type IN ('ARTICLE', 'ISSUE', 'TOPIC', 'FINDING', 'EVENT', 'REPORT', 'RUN'));

ALTER TABLE agent_quota_reservations DROP CONSTRAINT ck_agent_quota_task;
ALTER TABLE agent_quota_reservations ADD CONSTRAINT ck_agent_quota_task
    CHECK (agent_task IN (
        'ANALYZE', 'SELF_CRITIQUE', 'VERIFY_EVIDENCE', 'REPORT', 'EXPLORE',
        'INSIGHT', 'INVESTIGATE', 'KEYWORD_STRATEGY'
    ));
