CREATE TABLE topic_delivery_policies (
    topic_id NUMBER PRIMARY KEY REFERENCES news_topics(id),
    enabled_yn CHAR(1) DEFAULT 'N' NOT NULL CHECK (enabled_yn IN ('Y','N')),
    run_yn CHAR(1) DEFAULT 'Y' NOT NULL CHECK (run_yn IN ('Y','N')),
    daily_yn CHAR(1) DEFAULT 'N' NOT NULL CHECK (daily_yn IN ('Y','N')),
    group_ids CLOB DEFAULT '[]' NOT NULL CHECK (group_ids IS JSON),
    recipient_ids CLOB DEFAULT '[]' NOT NULL CHECK (recipient_ids IS JSON),
    channel_ids CLOB DEFAULT '[]' NOT NULL CHECK (channel_ids IS JSON)
);
CREATE TABLE report_notification_outbox (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id NUMBER NOT NULL REFERENCES news_reports(id),
    recipient_id NUMBER NOT NULL REFERENCES notification_recipients(id),
    channel_id NUMBER NOT NULL REFERENCES notification_channels(id),
    batch_id VARCHAR2(36) NOT NULL REFERENCES notification_delivery_batches(id),
    recipient_name VARCHAR2(100) NOT NULL,
    address VARCHAR2(500) NOT NULL,
    subject VARCHAR2(1000),
    body CLOB NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    attempt_count NUMBER DEFAULT 0 NOT NULL,
    available_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    processing_at TIMESTAMP,
    last_error VARCHAR2(1000),
    CONSTRAINT uq_report_auto_target UNIQUE(report_id, recipient_id, channel_id),
    CONSTRAINT ck_report_auto_status CHECK(status IN ('PENDING','PROCESSING','SENT','FAILED','SKIPPED','UNKNOWN'))
);
CREATE INDEX ix_report_outbox_claim ON report_notification_outbox(status,available_at,id);
CREATE TABLE telegram_connection_tokens (
    token_hash VARCHAR2(64) PRIMARY KEY,
    recipient_id NUMBER NOT NULL REFERENCES notification_recipients(id),
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP
);
CREATE INDEX ix_telegram_token_recipient ON telegram_connection_tokens(recipient_id,expires_at);
CREATE TABLE telegram_update_cursor (
    id NUMBER PRIMARY KEY CHECK(id=1),
    next_update_id NUMBER DEFAULT 0 NOT NULL,
    lease_until TIMESTAMP
);
INSERT INTO telegram_update_cursor(id,next_update_id) VALUES(1,0);
