-- M3 수집 실행. 컬럼은 Notion `수집실행(runs)` 3개 명세의 응답 필드에서 역산했다.
-- plan-final §3이 가리키는 plan-news-agent.md §4가 docs에 없어서, 명세가 요구하는 값을 기준으로 삼는다.

CREATE TABLE news_collection_runs (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status           VARCHAR2(20) NOT NULL,
    trigger_type     VARCHAR2(20) NOT NULL,
    idempotency_key  VARCHAR2(100),
    force_refresh_yn CHAR(1) DEFAULT 'N' NOT NULL,
    started_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    finished_at      TIMESTAMP,
    -- scanned = new + updated + skipped. 조합별 값을 run_items에 두고 여기에 합계를 둔다.
    -- 목록 조회가 실행마다 조합을 훑지 않게 하려는 비정규화다.
    scanned_count    NUMBER(10) DEFAULT 0 NOT NULL,
    new_count        NUMBER(10) DEFAULT 0 NOT NULL,
    updated_count    NUMBER(10) DEFAULT 0 NOT NULL,
    skipped_count    NUMBER(10) DEFAULT 0 NOT NULL,
    -- news_reports는 M5에 생긴다. 그때 FK를 건다.
    report_id        NUMBER,
    CONSTRAINT ck_run_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED')),
    CONSTRAINT ck_run_counts_nonnegative CHECK (
        scanned_count >= 0 AND new_count >= 0 AND updated_count >= 0 AND skipped_count >= 0
    ),
    CONSTRAINT ck_run_counts_consistent CHECK (new_count + updated_count + skipped_count <= scanned_count),
    CONSTRAINT ck_run_trigger_type CHECK (trigger_type IN ('MANUAL', 'SCHEDULED')),
    CONSTRAINT ck_run_force_refresh_yn CHECK (force_refresh_yn IN ('Y', 'N'))
);

-- 명세는 "같은 키로 **이미 실행 중인** run"만 중복으로 본다. 끝난 run의 키는 다시 쓸 수 있어야 하므로
-- 전역 유니크를 걸 수 없다. 진행 중일 때만 유니크한 함수 기반 인덱스로 버튼 연타를 DB에서 막는다.
CREATE UNIQUE INDEX uq_run_active_idempotency_key
    ON news_collection_runs (CASE WHEN status IN ('PENDING', 'RUNNING') THEN idempotency_key END);

-- 내역 조회가 최신순이다.
CREATE INDEX ix_run_started_at ON news_collection_runs (started_at DESC);

-- 상세 조회의 breakdown. 한 행 = 조합(주제 × 소스) 1건.
-- 목록 조회의 topicId 필터도 이 테이블로 푼다 — "해당 주제를 포함한 실행"이 곧 이 행의 존재다.
CREATE TABLE news_collection_run_items (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        NUMBER NOT NULL,
    topic_id      NUMBER NOT NULL,
    source_id     NUMBER NOT NULL,
    status        VARCHAR2(20) NOT NULL,
    scanned_count NUMBER(10) DEFAULT 0 NOT NULL,
    new_count     NUMBER(10) DEFAULT 0 NOT NULL,
    updated_count NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_run_item_run FOREIGN KEY (run_id) REFERENCES news_collection_runs (id),
    CONSTRAINT fk_run_item_topic FOREIGN KEY (topic_id) REFERENCES news_topics (id),
    CONSTRAINT fk_run_item_source FOREIGN KEY (source_id) REFERENCES news_sources (id),
    CONSTRAINT ck_run_item_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'SKIPPED')),
    CONSTRAINT ck_run_item_counts_nonnegative CHECK (
        scanned_count >= 0 AND new_count >= 0 AND updated_count >= 0
    ),
    CONSTRAINT ck_run_item_counts_consistent CHECK (new_count + updated_count <= scanned_count),
    CONSTRAINT uq_run_item UNIQUE (run_id, topic_id, source_id)
);

CREATE INDEX ix_run_item_topic ON news_collection_run_items (topic_id);

-- 크롤러 실패는 수집 전체를 실패로 만들지 않는다. 여기에 쌓이고 실행 상태가 PARTIAL이 된다.
CREATE TABLE news_collection_run_warnings (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        NUMBER NOT NULL,
    -- 소스와 무관한 경고도 있어 nullable이다.
    source_id     NUMBER,
    code          VARCHAR2(50) NOT NULL,
    message       VARCHAR2(1000),
    article_count NUMBER(10) DEFAULT 0 NOT NULL,
    occurred_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_run_warning_run FOREIGN KEY (run_id) REFERENCES news_collection_runs (id),
    CONSTRAINT fk_run_warning_source FOREIGN KEY (source_id) REFERENCES news_sources (id)
);

CREATE INDEX ix_run_warning_run ON news_collection_run_warnings (run_id);

CREATE TABLE news_articles (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 최초 관측의 주제·소스다(plan-final §3-1). 실행별·주제별 관측은 news_collection_run_articles가 갖는다.
    topic_id          NUMBER NOT NULL,
    source_id         NUMBER NOT NULL,
    -- §2-8. 검색 결과 URL은 매우 길 수 있어 Oracle 인덱스 키 길이 제한에 걸린다. SHA-256 64자로 줄여 건다.
    url_hash          VARCHAR2(64) NOT NULL,
    canonical_url     VARCHAR2(2000) NOT NULL,
    title             VARCHAR2(1000) NOT NULL,
    summary           CLOB,
    body              CLOB,
    -- 본문이 바뀌었는지 판정한다. 같으면 SKIPPED, 다르면 UPDATED.
    content_hash      VARCHAR2(64),
    language          VARCHAR2(5),
    source_name       VARCHAR2(200),
    -- 해외 기사의 발행 시각은 오프셋이 의미를 갖는다. 서버가 만드는 시각과 달리 WITH TIME ZONE으로 둔다.
    published_at      TIMESTAMP WITH TIME ZONE,
    fetch_status      VARCHAR2(30) NOT NULL,
    first_seen_run_id NUMBER,
    last_seen_run_id  NUMBER,
    collected_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP,
    CONSTRAINT fk_article_topic FOREIGN KEY (topic_id) REFERENCES news_topics (id),
    CONSTRAINT fk_article_source FOREIGN KEY (source_id) REFERENCES news_sources (id),
    CONSTRAINT fk_article_first_run FOREIGN KEY (first_seen_run_id) REFERENCES news_collection_runs (id),
    CONSTRAINT fk_article_last_run FOREIGN KEY (last_seen_run_id) REFERENCES news_collection_runs (id),
    CONSTRAINT ck_article_fetch_status
        CHECK (fetch_status IN ('METADATA_ONLY', 'FULLTEXT', 'FULLTEXT_BLOCKED', 'ROBOTS_DISALLOWED', 'FETCH_FAILED')),
    -- §2-6 "중복은 url_hash로 제거한다". 같은 기사가 여러 주제에 걸려도 1건만 남고 나머지는 skippedCount로 센다.
    CONSTRAINT uq_article_url_hash UNIQUE (url_hash)
);

CREATE INDEX ix_article_topic_published ON news_articles (topic_id, published_at DESC);
CREATE INDEX ix_article_source ON news_articles (source_id);

-- §2-8. 현재 상태만으로는 "무엇이 언제 바뀌었는지"를 추적할 수 없다.
CREATE TABLE news_article_versions (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id   NUMBER NOT NULL,
    run_id       NUMBER,
    version_no   NUMBER(6) NOT NULL,
    title        VARCHAR2(1000),
    body         CLOB,
    content_hash VARCHAR2(64),
    changed_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_article_version_article FOREIGN KEY (article_id) REFERENCES news_articles (id),
    CONSTRAINT fk_article_version_run FOREIGN KEY (run_id) REFERENCES news_collection_runs (id),
    CONSTRAINT uq_article_version UNIQUE (article_id, version_no)
);

-- 관측 이력. 기사 행은 url_hash로 전역 1건이지만, "run 42에서 관측된 기사"는 그것만으로 복원되지 않는다.
-- last_seen_run_id는 다음 실행에 덮이고, 같은 URL이 다른 주제·소스에서 발견되면 첫 행의 값만 남는다.
-- Notion 기사 목록 명세의 runId/topicId/sourceId 필터와 행마다 붙는 changeType이 이 테이블을 요구한다.
CREATE TABLE news_collection_run_articles (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id      NUMBER NOT NULL,
    article_id  NUMBER NOT NULL,
    topic_id    NUMBER NOT NULL,
    source_id   NUMBER NOT NULL,
    -- 명세의 필터는 NEW/UPDATED뿐이지만, 안 바뀐 관측도 남겨야 skippedCount를 이력에서 재현할 수 있다.
    change_type VARCHAR2(20) NOT NULL,
    observed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_run_article_run FOREIGN KEY (run_id) REFERENCES news_collection_runs (id),
    CONSTRAINT fk_run_article_article FOREIGN KEY (article_id) REFERENCES news_articles (id),
    CONSTRAINT fk_run_article_topic FOREIGN KEY (topic_id) REFERENCES news_topics (id),
    CONSTRAINT fk_run_article_source FOREIGN KEY (source_id) REFERENCES news_sources (id),
    CONSTRAINT ck_run_article_change_type CHECK (change_type IN ('NEW', 'UPDATED', 'UNCHANGED')),
    CONSTRAINT uq_run_article UNIQUE (run_id, article_id, topic_id, source_id)
);

CREATE INDEX ix_run_article_article ON news_collection_run_articles (article_id);
CREATE INDEX ix_run_article_topic ON news_collection_run_articles (topic_id);

-- F6 Conditional GET 상태. 구현은 후속 이슈지만 마이그레이션이 쪼개지지 않게 컬럼을 여기서 만든다.
-- 다음 요청에 If-None-Match / If-Modified-Since로 실어 보내고 304면 파싱을 건너뛴다.
ALTER TABLE news_sources ADD (
    etag            VARCHAR2(200),
    last_modified   VARCHAR2(100),
    last_fetched_at TIMESTAMP
);
