-- Capability secrets are never persisted; delivery bodies necessarily contain the recipient's link.
CREATE TABLE news_feedback_capabilities (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR2(64 CHAR) NOT NULL UNIQUE,
    report_id NUMBER(19) NOT NULL REFERENCES news_reports(id),
    recipient_id NUMBER(19) NOT NULL REFERENCES notification_recipients(id),
    snapshot_json CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_feedback_snapshot CHECK (snapshot_json IS JSON)
);
CREATE INDEX ix_feedback_cap_report ON news_feedback_capabilities(report_id,recipient_id);

CREATE TABLE news_feedback (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capability_id NUMBER(19) NOT NULL REFERENCES news_feedback_capabilities(id),
    recipient_id NUMBER(19) NOT NULL REFERENCES notification_recipients(id),
    report_id NUMBER(19) NOT NULL REFERENCES news_reports(id),
    item_id NUMBER(19) NOT NULL,
    category VARCHAR2(30 CHAR) NOT NULL,
    user_comment VARCHAR2(2000 CHAR) NOT NULL,
    allow_personalization CHAR(1) NOT NULL,
    idempotency_key VARCHAR2(100 CHAR) NOT NULL,
    request_hash VARCHAR2(64 CHAR) NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    verdict VARCHAR2(30 CHAR),
    diagnosis CLOB,
    input_json CLOB NOT NULL,
    review_json CLOB,
    created_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    CONSTRAINT uq_feedback_request UNIQUE(capability_id,idempotency_key),
    CONSTRAINT uq_feedback_item UNIQUE(recipient_id,report_id,item_id),
    CONSTRAINT ck_feedback_category CHECK(category IN ('PREFERENCE','TOPIC_MISMATCH','SUMMARY_ERROR','WRONG_CLUSTER','OTHER')),
    CONSTRAINT ck_feedback_consent CHECK(allow_personalization IN ('Y','N') AND (allow_personalization='N' OR category='PREFERENCE')),
    CONSTRAINT ck_feedback_status CHECK(status IN ('PENDING','PROCESSING','COMPLETED','FAILED')),
    CONSTRAINT ck_feedback_input CHECK(input_json IS JSON),
    CONSTRAINT ck_feedback_review CHECK(review_json IS JSON)
);

CREATE TABLE news_feedback_policies (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id NUMBER(19) NOT NULL REFERENCES notification_recipients(id),
    topic_id NUMBER(19) NOT NULL REFERENCES news_topics(id),
    topic_name VARCHAR2(200 CHAR) NOT NULL,
    instruction VARCHAR2(1000 CHAR) NOT NULL,
    instruction_hash VARCHAR2(64 CHAR) NOT NULL,
    version NUMBER(10) NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    source_feedback_id NUMBER(19) NOT NULL REFERENCES news_feedback(id),
    created_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    CONSTRAINT ck_feedback_policy_status CHECK(status IN ('ACTIVE','REVOKED'))
);
CREATE INDEX ix_feedback_policy_scope ON news_feedback_policies(recipient_id,topic_id,status,created_at);

CREATE TABLE news_feedback_jobs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_key VARCHAR2(200 CHAR) NOT NULL UNIQUE,
    kind VARCHAR2(20 CHAR) NOT NULL,
    feedback_id NUMBER(19) REFERENCES news_feedback(id),
    recipient_id NUMBER(19) NOT NULL REFERENCES notification_recipients(id),
    report_id NUMBER(19) NOT NULL REFERENCES news_reports(id),
    topic_id NUMBER(19) NOT NULL REFERENCES news_topics(id),
    input_json CLOB NOT NULL,
    result_json CLOB,
    status VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    attempt_count NUMBER(5) DEFAULT 0 NOT NULL,
    claim_key VARCHAR2(36 CHAR),
    created_at TIMESTAMP NOT NULL,
    available_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    CONSTRAINT ck_feedback_job_kind CHECK(kind IN ('REVIEW','EVALUATE')),
    CONSTRAINT ck_feedback_job_status CHECK(status IN ('PENDING','PROCESSING','COMPLETED','FAILED')),
    CONSTRAINT ck_feedback_job_input CHECK(input_json IS JSON),
    CONSTRAINT ck_feedback_job_result CHECK(result_json IS JSON)
);
CREATE INDEX ix_feedback_job_queue ON news_feedback_jobs(status,available_at);
CREATE INDEX ix_feedback_job_report ON news_feedback_jobs(report_id,recipient_id,kind);
