-- M4 분석 결과. 한 실행에서 같은 기사를 여러 주제·소스가 발견해도 분석은 한 번만 남긴다.
CREATE TABLE news_findings (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        NUMBER NOT NULL,
    article_id    NUMBER NOT NULL,
    change_type   VARCHAR2(20) NOT NULL,
    summary       CLOB NOT NULL,
    key_points    CLOB DEFAULT '[]' NOT NULL,
    intent        VARCHAR2(200),
    sentiment     VARCHAR2(20) NOT NULL,
    risk_level    VARCHAR2(20) NOT NULL,
    relevance     VARCHAR2(20) NOT NULL,
    category      VARCHAR2(50) NOT NULL,
    -- M4 화면은 이 JSON을 문장 단위 본문 sections로 렌더링한다.
    -- 각 index는 key_points.evidence가 가리키는 안정적인 근거 번호다.
    sections      CLOB DEFAULT '[]' NOT NULL,
    analyzed_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_finding_run FOREIGN KEY (run_id) REFERENCES news_collection_runs (id),
    CONSTRAINT fk_finding_article FOREIGN KEY (article_id) REFERENCES news_articles (id),
    CONSTRAINT uq_finding_run_article UNIQUE (run_id, article_id),
    CONSTRAINT ck_finding_change_type CHECK (change_type IN ('NEW', 'UPDATED')),
    CONSTRAINT ck_finding_sentiment CHECK (sentiment IN ('POSITIVE', 'NEUTRAL', 'NEGATIVE')),
    CONSTRAINT ck_finding_risk_level CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT ck_finding_relevance CHECK (relevance IN ('IMPORTANT', 'WATCH', 'REFERENCE')),
    CONSTRAINT ck_finding_key_points_json CHECK (key_points IS JSON),
    CONSTRAINT ck_finding_sections_json CHECK (sections IS JSON)
);

CREATE INDEX ix_finding_article_latest ON news_findings (article_id, analyzed_at DESC);
CREATE INDEX ix_finding_run ON news_findings (run_id);
CREATE INDEX ix_finding_filters ON news_findings (relevance, risk_level, category);
