-- Report perspective analysis has its own cache; issue insights retain their existing contract.
CREATE TABLE news_report_insights (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id NUMBER(19) NOT NULL REFERENCES news_reports(id),
    audience VARCHAR2(30) NOT NULL,
    input_hash VARCHAR2(64) NOT NULL,
    prompt_version VARCHAR2(50) NOT NULL,
    rubric_version VARCHAR2(50) NOT NULL,
    payload_json CLOB NOT NULL,
    input_finding_count NUMBER(3) NOT NULL,
    llm_provider VARCHAR2(30),
    llm_model VARCHAR2(100),
    input_tokens NUMBER(19),
    output_tokens NUMBER(19),
    cost_usd NUMBER(12,6),
    credits NUMBER(10,3),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_report_insight UNIQUE(report_id, audience, input_hash, prompt_version, rubric_version),
    CONSTRAINT ck_report_insight_audience CHECK(audience IN
        ('CHIP_MAKER', 'EQUIPMENT_MAKER', 'MARKET_INVESTOR', 'IT_INFRA')),
    CONSTRAINT ck_report_insight_payload CHECK(payload_json IS JSON),
    CONSTRAINT ck_report_insight_count CHECK(input_finding_count BETWEEN 1 AND 50)
);
CREATE INDEX ix_report_insight_created ON news_report_insights(report_id, created_at DESC);
