-- M5 실행 단위 보고서. run 하나에는 보고서가 최대 하나만 생긴다.
CREATE TABLE news_reports (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         NUMBER NOT NULL,
    title          VARCHAR2(500) NOT NULL,
    markdown_body  CLOB NOT NULL,
    model_name     VARCHAR2(100) NOT NULL,
    generated_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_report_run FOREIGN KEY (run_id) REFERENCES news_collection_runs (id),
    CONSTRAINT uq_report_run UNIQUE (run_id)
);

CREATE INDEX ix_report_generated_at ON news_reports (generated_at DESC, id DESC);

-- V4에서 M5까지 FK 없이 보관하던 역참조를 실제 보고서에 연결한다.
-- UNIQUE는 같은 보고서를 둘 이상의 run이 가리키는 잘못된 연결도 막는다.
ALTER TABLE news_collection_runs ADD CONSTRAINT uq_run_report UNIQUE (report_id);
ALTER TABLE news_collection_runs ADD CONSTRAINT fk_run_report
    FOREIGN KEY (report_id) REFERENCES news_reports (id);
