-- A0 Spring -> FastAPI agent 호출 감사 로그. 사용량과 멱등성의 정본은 Oracle이 소유한다.
CREATE TABLE agent_runs (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_run_id NUMBER REFERENCES news_collection_runs (id),
    idempotency_key   VARCHAR2(200) NOT NULL,
    agent_task        VARCHAR2(50) NOT NULL,
    target_type       VARCHAR2(30) NOT NULL,
    target_id         NUMBER,
    status            VARCHAR2(30) NOT NULL,
    failure_code      VARCHAR2(100),
    failure_message   VARCHAR2(1000),
    prompt_version    VARCHAR2(50),
    llm_provider      VARCHAR2(30),
    llm_model         VARCHAR2(100),
    llm_plan          VARCHAR2(10),
    input_tokens      NUMBER,
    output_tokens     NUMBER,
    cost_usd          NUMBER(12,6),
    credits           NUMBER(10,3),
    request_hash      VARCHAR2(64),
    started_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    finished_at       TIMESTAMP,
    CONSTRAINT uq_agent_idempotency UNIQUE (idempotency_key),
    CONSTRAINT ck_agent_task CHECK (agent_task IN ('ANALYZE', 'VERIFY_EVIDENCE', 'REPORT', 'EXPLORE')),
    CONSTRAINT ck_agent_target_type CHECK (target_type IN ('ARTICLE', 'FINDING', 'EVENT', 'REPORT', 'RUN')),
    CONSTRAINT ck_agent_status CHECK (status IN ('SUCCESS', 'FAILED', 'SKIPPED', 'REUSED', 'MOCK')),
    CONSTRAINT ck_agent_plan CHECK (llm_plan IS NULL OR llm_plan IN ('FREE', 'PAID'))
);

CREATE INDEX ix_agent_run_usage ON agent_runs (llm_plan, started_at);
CREATE INDEX ix_agent_run_collection ON agent_runs (collection_run_id, agent_task);
